### ISSUE TITLE
One large map won't optimize

### ISSUE THREAD

**Issue by Guinfan72** [watermelonwolverine/fvttoptimizer#11]
File is 14.6 MB, the rest of my maps were changed to .webp, though they were all under 9MB. The error message is:

root - ERROR - Traceback (most recent call last):
  File "cli_wrapper\main.py", line 235, in main
  File "cli_wrapper\main.py", line 229, in do_run
  File "cli_wrapper\main.py", line 81, in perform_optimization_with
  File "fvttoptimizer\optimizer.py", line 44, in optimize
  File "fvttoptimizer\__file_optimizer.py", line 34, in maybe_optimize
  File "fvttoptimizer\__file_optimizer.py", line 48, in __maybe_optimize2
  File "fvttoptimizer\__file_optimizer.py", line 53, in __optimize
  File "fvttoptimizer\__file_optimizer.py", line 74, in __encode_as_webp
  File "PIL\Image.py", line 3109, in open
  File "PIL\Image.py", line 3096, in _open_core
  File "PIL\Image.py", line 3005, in _decompression_bomb_check
PIL.Image.DecompressionBombError: Image size (206308971 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

An internal error occurred: Traceback (most recent call last):
  File "cli_wrapper\main.py", line 235, in main
  File "cli_wrapper\main.py", line 229, in do_run
  File "cli_wrapper\main.py", line 81, in perform_optimization_with
  File "fvttoptimizer\optimizer.py", line 44, in optimize
  File "fvttoptimizer\__file_optimizer.py", line 34, in maybe_optimize
  File "fvttoptimizer\__file_optimizer.py", line 48, in __maybe_optimize2
  File "fvttoptimizer\__file_optimizer.py", line 53, in __optimize
  File "fvttoptimizer\__file_optimizer.py", line 74, in __encode_as_webp
  File "PIL\Image.py", line 3109, in open
  File "PIL\Image.py", line 3096, in _open_core
  File "PIL\Image.py", line 3005, in _decompression_bomb_check
PIL.Image.DecompressionBombError: Image size (206308971 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

**Comment by Danny-Matelot** [comment]
Webp only allows up to 16,383 x 16,383 pixels.

So you must have a file larger than that, making fvvtoptimizer crash

**Comment by watermelonwolverine** [comment]
Yes, @Danny-Matelot, I also think that's the issue. Should there be a next version I will add a catch for this problem and put out a better error message so people without programming background will understand the issue.
